# Cox Proportional Hazards

### Wstęp
&emsp;Model proporcjonalnego hazardu Cox'a jest modelem pozwalającym ocenić wpływ wielu czynników na funkcję hazardu (chwilowe natężenie ryzyka). W naszym przypadku oceniać będziemy wpływ na ryzyko zapłaty (zdarzenie).

&emsp; Przy budownie modelu uwzględnimy następujące cechy:
* `total_open_amount` *(kwota faktury)*
* `days_to_due` *(po ilu dniach płatność)*
* `invoice_age` *(wiek faktury)*
* `avg_delay_customer` *(średnie opóźnienie klienta)*
* `cust_payment_terms` *(warunki płatności)*
* `invoice_currency` *(waluta)*
* `segment` *(BE lub SME)*

### Biblioteki i przygotowanie danych
&emsp; Zacznijmy od zaimportowania niezbędnych narzędzi oraz przygotowania danych. Zostawimy jedynie kolumny odpowiadające interesującym nas cechom.

In [20]:
import pandas as pd
from lifelines import CoxPHFitter
import matplotlib.pyplot as plt

df = pd.read_csv('../data/dataset_survclean.csv')

df['document_create_date_dt'] = pd.to_datetime(df['document_create_date_dt'])
df = df.sort_values('document_create_date_dt')

features = [
    'total_open_amount',
    'days_to_due',
    'invoice_age',
    'avg_delay_customer',
    'cust_payment_terms',
    'invoice_currency',
    'segment',
    'time_days', 
    'event'
]

cox_df = df[features].copy()

cox_df = pd.get_dummies(cox_df, columns=['cust_payment_terms', 'invoice_currency', 'segment'], drop_first=True)
cox_df = cox_df.dropna()
cox_df = cox_df.astype(float)

splt_id = int(len(cox_df) * 0.8)
train_df = cox_df.iloc[:splt_id]
test_df = cox_df.iloc[splt_id:]

print(f"Zbiór treningowy: {len(train_df)} faktur\nZbiór testowy: {len(test_df)} faktur")

display(train_df.head())

Zbiór treningowy: 39070 faktur
Zbiór testowy: 9768 faktur

,total_open_amount,days_to_due,invoice_age,avg_delay_customer,time_days,event,cust_payment_terms_NA10,cust_payment_terms_NA32,cust_payment_terms_NAA8,cust_payment_terms_NAAW,...,cust_payment_terms_NAVF,cust_payment_terms_NAVQ,cust_payment_terms_NAVR,cust_payment_terms_NAWN,cust_payment_terms_NAWP,cust_payment_terms_NAWU,cust_payment_terms_NAX2,cust_payment_terms_OTHER,invoice_currency_USD,segment_SME
0,13760.55,34.0,30.0,0.0,28.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1,28225.48,32.0,30.0,0.0,62.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
53,4445.93,16.0,15.0,0.2,11.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
52,51473.49,16.0,15.0,0.0,17.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
51,4678.12,20.0,15.0,0.0,19.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Model
&emsp; Pozostało dopasować model Coxa do badanego zbioru danych. Kolumną zawierającą informacje na temat upływu czasu jest `time_days`, a kolumną informującą o wystąpieniu zdarzenia jest kolumna `event`.

In [21]:
cph = CoxPHFitter()

cph.fit(train_df, duration_col='time_days', event_col='event')

#### Załozenie o proporcjinalności hazardów
&emsp; Model Coxa opiera się na załozeniu o proporcjonalności hazardów. Załozenie to mowi, ze stosunek hazardu dla dowolnych dwoch obserwacji musi być stały w czasie. W kontekście projektu oznacza to, ze wpływ cechy na prawdopodobieństwo zapłacenia faktury nie moze się zmieniać wraz upływem dni. Wpływ ten musi być ponadto liniowy.

&emsp; Jeśli to załozenie jest łamane model traci na wiarygodności. W celu jego weryfikacji wykorzystamy test reszt Schoenfelda.

In [22]:
results = cph.check_assumptions(train_df, p_value_threshold=0.05, show_plots=False)

The ``p_value_threshold`` is set at 0.05. Even under the null hypothesis of no violations, some
covariates will be below the threshold by chance. This is compounded when there are many covariates.
Similarly, when there are lots of observations, even minor deviances from the proportional hazard
assumption will be flagged.

With that in mind, it's best to use a combination of statistical tests and visual tests to determine
the most serious violations. Produce visual plots using ``check_assumptions(..., show_plots=True)``
and looking for non-constant lines. See link [A] below for a full example.

1. Variable 'total_open_amount' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'total_open_amount' might be incorrect. That is,
there may be non-linear terms missing. The proportional hazard test used is very sensitive to
incorrect functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'total_open_amount' using pd.cut, and then specify it in
`strata=['total_open_amount', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


2. Variable 'days_to_due' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'days_to_due' might be incorrect. That is, there
may be non-linear terms missing. The proportional hazard test used is very sensitive to incorrect
functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'days_to_due' using pd.cut, and then specify it in
`strata=['days_to_due', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


3. Variable 'invoice_age' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'invoice_age' might be incorrect. That is, there
may be non-linear terms missing. The proportional hazard test used is very sensitive to incorrect
functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'invoice_age' using pd.cut, and then specify it in
`strata=['invoice_age', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


4. Variable 'avg_delay_customer' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'avg_delay_customer' might be incorrect. That is,
there may be non-linear terms missing. The proportional hazard test used is very sensitive to
incorrect functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'avg_delay_customer' using pd.cut, and then specify it in
`strata=['avg_delay_customer', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


5. Variable 'cust_payment_terms_NA10' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NA10',
...]` in the call in `.fit`. See documentation in link [E] below.

6. Variable 'cust_payment_terms_NA32' failed the non-proportional test: p-value is 0.0032.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NA32',
...]` in the call in `.fit`. See documentation in link [E] below.

7. Variable 'cust_payment_terms_NAA8' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAA8',
...]` in the call in `.fit`. See documentation in link [E] below.

8. Variable 'cust_payment_terms_NAAX' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAAX',
...]` in the call in `.fit`. See documentation in link [E] below.

9. Variable 'cust_payment_terms_NAC6' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAC6',
...]` in the call in `.fit`. See documentation in link [E] below.

10. Variable 'cust_payment_terms_NAD1' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAD1',
...]` in the call in `.fit`. See documentation in link [E] below.

11. Variable 'cust_payment_terms_NAGD' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAGD',
...]` in the call in `.fit`. See documentation in link [E] below.

12. Variable 'cust_payment_terms_NAH4' failed the non-proportional test: p-value is 0.0038.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAH4',
...]` in the call in `.fit`. See documentation in link [E] below.

13. Variable 'cust_payment_terms_NAM1' failed the non-proportional test: p-value is 0.0053.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAM1',
...]` in the call in `.fit`. See documentation in link [E] below.

14. Variable 'cust_payment_terms_NAM2' failed the non-proportional test: p-value is 0.0104.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAM2',
...]` in the call in `.fit`. See documentation in link [E] below.

15. Variable 'cust_payment_terms_NAU5' failed the non-proportional test: p-value is 0.0005.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAU5',
...]` in the call in `.fit`. See documentation in link [E] below.

16. Variable 'cust_payment_terms_NAVE' failed the non-proportional test: p-value is 0.0001.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAVE',
...]` in the call in `.fit`. See documentation in link [E] below.

17. Variable 'cust_payment_terms_NAVR' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAVR',
...]` in the call in `.fit`. See documentation in link [E] below.

18. Variable 'cust_payment_terms_NAWN' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAWN',
...]` in the call in `.fit`. See documentation in link [E] below.

19. Variable 'cust_payment_terms_NAX2' failed the non-proportional test: p-value is 0.0027.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAX2',
...]` in the call in `.fit`. See documentation in link [E] below.

20. Variable 'cust_payment_terms_OTHER' failed the non-proportional test: p-value is 0.0469.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_OTHER',
...]` in the call in `.fit`. See documentation in link [E] below.

21. Variable 'segment_SME' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['segment_SME', ...]` in the
call in `.fit`. See documentation in link [E] below.

---
[A]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html
[B]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Bin-variable-and-stratify-on-it
[C]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Introduce-time-varying-covariates
[D]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Modify-the-functional-form
[E]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Stratification

&emsp;Z tabeli odczytujemy, że dla wielu zmiennych (m.in. `avg_delay_customer`, `days_to_due`, `invoice_age`, `segment_SME`, `total_open_amount`), wartość p-value jest niższa niż próg 0.05. Oznacza to, że hipoteza zerowa testu Schoenfelda jest fałszywa. Co za tym idzie, wpływ cech na "ryzyko" opłacenia faktury nie jest stały w czasie.

&emsp;Mamy do czynienia ze złamaniem podstawowego założenia modelu Coxa, co pozwala wyciągnąć wniosek, że modele nieliniowe jak Random Survival Forest poradzą sobie z predykcją zauważalnie lepiej.

#### Ewaluacja modelu
&emsp; Bazując na budowie algorytmu do wyliczenia funkcji częściowej wiarygodności (partial likelihood), w której wzorze wspolczynnik dla kazdej cechy jest stały w czasie, otrzymane w tabeli wyniki mozemy interpretować jako uśredniowy wpływ poszczególnych cech na "ryzyko" zapłaty.

&emsp; Wywołanie `cph.print_summary` dostarczy nam informacji o m.in:
* Hazard Ratio (`exp(coef)`): Dla zmiennych kategorycznych stosunek hazardu między podmiotem posiadającym i nieposiadającym danej cechy. Dla zmiennych ciągłych zmiana intensywności spłaty przy wzroście cechy o jedną jednostkę. Interpretacja:
    * HR > 1: zwiększone ryzyko
    * HR = 1: brak wpływu
    * HR < 1: zmniejszone ryzyko
* C-index (`Concordance`): Odsetek par, które model poprawnie uporządkował pod względem czasu do wystąpienia zdarzenia.

In [25]:
cph.print_summary()
test_cid = cph.score(test_df, scoring_method="concordance_index")

print(f"test C-index: {test_cid: .4f}")

<lifelines.CoxPHFitter: fitted with 39070 total observations, 38 right-censored observations>
             duration col = 'time_days'
                event col = 'event'
      baseline estimation = breslow
   number of observations = 39070
number of events observed = 39032
   partial log-likelihood = -359928.34
         time fit was run = 2026-08-10 14:35:11 UTC

---
                          coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
total_open_amount         0.00      1.00      0.00            0.00            0.00                1.00                1.00
days_to_due              -0.06      0.94      0.00           -0.06           -0.06                0.94                0.94
invoice_age               0.03      1.04      0.00            0.03            0.04                1.03                1.04
avg_delay_customer       -0.04      0.96      0.00           -0.04           -0.04                0.96                0.96
cust_payment_terms_NA10   0.17      1.18      0.12           -0.07            0.40                0.93                1.50
cust_payment_terms_NA32  -0.68      0.51      0.12           -0.90           -0.45                0.41                0.64
cust_payment_terms_NAA8   0.03      1.03      0.11           -0.18            0.24                0.84                1.27
cust_payment_terms_NAAW   0.30      1.35      0.14            0.03            0.56                1.03                1.75
cust_payment_terms_NAAX   0.26      1.30      0.11            0.05            0.48                1.05                1.62
cust_payment_terms_NAC6   0.18      1.20      0.11           -0.04            0.39                0.96                1.48
cust_payment_terms_NAD1  -0.49      0.61      0.11           -0.70           -0.27                0.49                0.77
cust_payment_terms_NAD5  -0.81      0.44      0.12           -1.06           -0.57                0.35                0.56
cust_payment_terms_NAG2  -0.78      0.46      0.11           -1.00           -0.57                0.37                0.57
cust_payment_terms_NAGD  -0.42      0.65      0.14           -0.70           -0.15                0.50                0.86
cust_payment_terms_NAH4   0.73      2.08      0.11            0.52            0.94                1.69                2.56
cust_payment_terms_NAM1   5.02    150.87      0.13            4.75            5.28              116.07              196.11
cust_payment_terms_NAM2   4.98    145.44      0.12            4.74            5.22              114.44              184.84
cust_payment_terms_NAM4   2.61     13.63      0.11            2.39            2.83               10.96               16.94
cust_payment_terms_NAU5   0.17      1.18      0.11           -0.06            0.39                0.95                1.47
cust_payment_terms_NAVE  -0.68      0.51      0.13           -0.93           -0.43                0.39                0.65
cust_payment_terms_NAVF  -0.60      0.55      0.14           -0.87           -0.33                0.42                0.72
cust_payment_terms_NAVQ  -0.64      0.53      0.17           -0.97           -0.31                0.38                0.73
cust_payment_terms_NAVR  -0.15      0.86      0.20           -0.54            0.24                0.58                1.27
cust_payment_terms_NAWN  -0.54      0.58      0.18           -0.90           -0.19                0.41                0.83
cust_payment_terms_NAWP  -0.87      0.42      0.17           -1.20           -0.53                0.30                0.59
cust_payment_terms_NAWU  -0.69      0.50      0.15           -0.97           -0.40                0.38                0.67
cust_payment_terms_NAX2  -0.48      0.62      0.12           -0.73           -0.24                0.48                0.79
cust_payment_terms_OTHER -0.44      0.64      0.11           -0.66           -0.23                0.52                0.80
invoice_currency_USD      0.10      1.10      0.11           -0.11            0.30                0.90                1.35
segment_SME              -0.09      0.91      0.02           -0.12           -0.06                0.88                0.94

                          cmp to      z      p  -log2(p)
covariate
total_open_amount           0.00  19.05 <0.005    266.22
days_to_due                 0.00 -55.99 <0.005       inf
invoice_age                 0.00  15.98 <0.005    188.62
avg_delay_customer          0.00 -31.75 <0.005    732.46
cust_payment_terms_NA10     0.00   1.38   0.17      2.58
cust_payment_terms_NA32     0.00  -5.84 <0.005     27.52
cust_payment_terms_NAA8     0.00   0.26   0.79      0.34
cust_payment_terms_NAAW     0.00   2.20   0.03      5.18
cust_payment_terms_NAAX     0.00   2.37   0.02      5.83
cust_payment_terms_NAC6     0.00   1.63   0.10      3.26
cust_payment_terms_NAD1     0.00  -4.36 <0.005     16.25
cust_payment_terms_NAD5     0.00  -6.61 <0.005     34.59
cust_payment_terms_NAG2     0.00  -7.07 <0.005     39.22
cust_payment_terms_NAGD     0.00  -3.01 <0.005      8.58
cust_payment_terms_NAH4     0.00   6.87 <0.005     37.17
cust_payment_terms_NAM1     0.00  37.49 <0.005   1019.63
cust_payment_terms_NAM2     0.00  40.71 <0.005       inf
cust_payment_terms_NAM4     0.00  23.51 <0.005    403.64
cust_payment_terms_NAU5     0.00   1.47   0.14      2.82
cust_payment_terms_NAVE     0.00  -5.37 <0.005     23.62
cust_payment_terms_NAVF     0.00  -4.39 <0.005     16.41
cust_payment_terms_NAVQ     0.00  -3.84 <0.005     12.98
cust_payment_terms_NAVR     0.00  -0.76   0.45      1.16
cust_payment_terms_NAWN     0.00  -3.01 <0.005      8.59
cust_payment_terms_NAWP     0.00  -5.10 <0.005     21.52
cust_payment_terms_NAWU     0.00  -4.68 <0.005     18.44
cust_payment_terms_NAX2     0.00  -3.88 <0.005     13.20
cust_payment_terms_OTHER    0.00  -4.04 <0.005     14.18
invoice_currency_USD        0.00   0.91   0.36      1.45
segment_SME                 0.00  -5.64 <0.005     25.82
---
Concordance = 0.78
Partial AIC = 719916.69
log-likelihood ratio test = 27771.14 on 30 df
-log2(p) of ll-ratio test = inf

test C-index:  0.4457