# Cox Proportional Hazards

## Wstęp
&emsp;Model proporcjonalnego hazardu Cox'a jest modelem pozwalającym ocenić wpływ wielu czynników na funkcję hazardu (chwilowe natężenie ryzyka). W naszym przypadku oceniać będziemy wpływ na ryzyko zapłaty (zdarzenie).

&emsp; Przy budownie modelu uwzględnimy następujące cechy:
* `total_open_amount` *(kwota faktury)*
* `days_to_due` *(po ilu dniach płatność)*
* `invoice_age` *(wiek faktury)*
* `avg_delay_customer` *(średnie opóźnienie klienta)*
* `cust_payment_terms` *(warunki płatności)*
* `invoice_currency` *(waluta)*
* `segment` *(BE lub SME)*

### Biblioteki i przygotowanie danych
&emsp; Zacznijmy od zaimportowania niezbędnych narzędzi oraz przygotowania danych. Zostawymy jedynie kolumny odpowiadające interesującym nas cechom.

In [15]:
import pandas as pd
from lifelines import CoxPHFitter
import matplotlib.pyplot as plt

df = pd.read_csv('../data/dataset_survclean.csv')

features = [
    'total_open_amount',
    'days_to_due',
    'invoice_age',
    'avg_delay_customer',
    'cust_payment_terms',
    'invoice_currency',
    'segment',
    'time_days', 
    'event'
]

cox_df = df[features].copy()

cox_df = pd.get_dummies(cox_df, columns=['cust_payment_terms', 'invoice_currency', 'segment'], drop_first=True)
cox_df = cox_df.dropna()
cox_df = cox_df.astype(float)

display(cox_df.head())

   total_open_amount  days_to_due  ...  invoice_currency_USD  segment_SME
0           54273.28         16.0  ...                   1.0          0.0
1           79656.60         20.0  ...                   1.0          1.0
2            2253.86         15.0  ...                   1.0          0.0
3            3299.70         11.0  ...                   0.0          0.0
4           33133.29         15.0  ...                   1.0          0.0

[5 rows x 81 columns]

### Model
&emsp; Pozostało dopasować model Coxa do badanego zbioru danych. Kolumną zawierającą informacje na temat upływu czasu jest `time_days`, a kolumną informującą o wystąpieniu zdarzenia jest kolumna `event`

In [16]:
cph = CoxPHFitter()

cph.fit(cox_df, duration_col='time_days', event_col='event')

/Users/bartekb/Bankrupt-Detector/venv/lib/python3.14/site-packages/lifelines/utils/__init__.py:1100: ConvergenceWarning: Column(s) ['cust_payment_terms_B052', 'cust_payment_terms_BR12', 'cust_payment_terms_C129', 'cust_payment_terms_CA60', 'cust_payment_terms_MC15', 'cust_payment_terms_NA31', 'cust_payment_terms_NABD', 'cust_payment_terms_NACE', 'cust_payment_terms_NACG', 'cust_payment_terms_NAD8', 'cust_payment_terms_NATH', 'cust_payment_terms_NATK', 'cust_payment_terms_NATL', 'cust_payment_terms_NATU', 'cust_payment_terms_NATV', 'cust_payment_terms_NATW', 'cust_payment_terms_NATX', 'cust_payment_terms_NATZ', 'cust_payment_terms_NAUW', 'cust_payment_terms_NAUY', 'cust_payment_terms_NAV2', 'cust_payment_terms_NAV9', 'cust_payment_terms_NAWM'] have very low variance. This may harm convergence. 1) Are you using formula's? Did you mean to add '-1' to the end. 2) Try dropping this redundant column before fitting if convergence fails.

  warnings.warn(dedent(warning_text), ConvergenceWarning)

In [17]:
cph.print_summary()

<lifelines.CoxPHFitter: fitted with 48838 total observations, 9681 right-censored observations>
             duration col = 'time_days'
                event col = 'event'
      baseline estimation = breslow
   number of observations = 48838
number of events observed = 39157
   partial log-likelihood = -393137.81
         time fit was run = 2026-07-28 17:08:02 UTC

---
                          coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
total_open_amount         0.00      1.00      0.00            0.00            0.00                1.00                1.00
days_to_due              -0.04      0.96      0.00           -0.04           -0.03                0.96                0.97
invoice_age              -0.10      0.90      0.03           -0.16           -0.05                0.85                0.96
avg_delay_customer       -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
cust_payment_terms_B052  -7.31      0.00      1.84          -10.93           -3.70                0.00                0.02
cust_payment_terms_BR12 -10.68      0.00      2.47          -15.53           -5.84                0.00                0.00
cust_payment_terms_BR56  -7.36      0.00      1.67          -10.63           -4.08                0.00                0.02
cust_payment_terms_C106 -11.83      0.00      2.78          -17.27           -6.38                0.00                0.00
cust_payment_terms_C129 -21.18      0.00    191.20         -395.93          353.57                0.00           3.59e+153
cust_payment_terms_CA10 -12.87      0.00      2.94          -18.63           -7.12                0.00                0.00
cust_payment_terms_CA30 -10.14      0.00      2.38          -14.80           -5.48                0.00                0.00
cust_payment_terms_CA60  -6.57      0.00      1.84          -10.17           -2.97                0.00                0.05
cust_payment_terms_CAB1 -13.54      0.00      3.24          -19.89           -7.19                0.00                0.00
cust_payment_terms_CAX2 -14.00      0.00      2.97          -19.82           -8.17                0.00                0.00
cust_payment_terms_MC15 -11.39      0.00      2.96          -17.20           -5.58                0.00                0.00
cust_payment_terms_NA10 -12.58      0.00      2.93          -18.33           -6.83                0.00                0.00
cust_payment_terms_NA25 -11.83      0.00      2.56          -16.84           -6.82                0.00                0.00
cust_payment_terms_NA31  -5.91      0.00      1.54           -8.93           -2.89                0.00                0.06
cust_payment_terms_NA32 -10.38      0.00      2.31          -14.91           -5.85                0.00                0.00
cust_payment_terms_NA38 -10.76      0.00      2.38          -15.42           -6.11                0.00                0.00
cust_payment_terms_NA3B -10.14      0.00      2.34          -14.73           -5.54                0.00                0.00
cust_payment_terms_NA3F -12.02      0.00      2.78          -17.47           -6.58                0.00                0.00
cust_payment_terms_NA84 -11.83      0.00      2.66          -17.06           -6.61                0.00                0.00
cust_payment_terms_NA8Q  -6.62      0.00      1.59           -9.75           -3.50                0.00                0.03
cust_payment_terms_NA9X -10.66      0.00      2.44          -15.45           -5.87                0.00                0.00
cust_payment_terms_NAA8 -12.40      0.00      2.79          -17.87           -6.93                0.00                0.00
cust_payment_terms_NAAW  -9.74      0.00      2.26          -14.16           -5.32                0.00                0.00
cust_payment_terms_NAAX -12.31      0.00      2.79          -17.78           -6.84                0.00                0.00
cust_payment_terms_NAB1 -13.04      0.00      3.22          -19.35           -6.73                0.00                0.00
cust_payment_terms_NABD  -6.05      0.00      1.72           -9.42           -2.69                0.00                0.07
cust_payment_terms_NABG  -8.94      0.00      1.96          -12.77           -5.11                0.00                0.01
cust_payment_terms_NAC6 -12.45      0.00      2.79          -17.92           -6.98                0.00                0.00
cust_payment_terms_NACB  -6.71      0.00      1.54           -9.73           -3.69                0.00                0.02
cust_payment_terms_NACE -24.93      0.00    122.08         -264.20          214.35                0.00            1.24e+93
cust_payment_terms_NACG -25.91      0.00    212.59         -442.57          390.75                0.00           5.04e+169
cust_payment_terms_NACH -24.99      0.00    101.46         -223.85          173.86                0.00            3.22e+75
cust_payment_terms_NAD1 -11.86      0.00      2.65          -17.05           -6.66                0.00                0.00
cust_payment_terms_NAD4  -9.20      0.00      2.09          -13.30           -5.09                0.00                0.01
cust_payment_terms_NAD5 -10.62      0.00      2.37          -15.26           -5.98                0.00                0.00
cust_payment_terms_NAD8 -13.56      0.00      3.10          -19.63           -7.48                0.00                0.00
cust_payment_terms_NAG2  -9.94      0.00      2.23          -14.30           -5.57                0.00                0.00
cust_payment_terms_NAGD  -6.16      0.00      1.40           -8.89           -3.42                0.00                0.03
cust_payment_terms_NAH4 -12.10      0.00      2.79          -17.57           -6.63                0.00                0.00
cust_payment_terms_NAM1 -12.34      0.00      3.02          -18.25           -6.42                0.00                0.00
cust_payment_terms_NAM2 -12.24      0.00      2.93          -17.99           -6.49                0.00                0.00
cust_payment_terms_NAM3 -13.15      0.00      2.83          -18.68           -7.61                0.00                0.00
cust_payment_terms_NAM4 -10.62      0.00      2.57          -15.65           -5.60                0.00                0.00
cust_payment_terms_NATH -13.72      0.00      3.27          -20.12           -7.32                0.00                0.00
cust_payment_terms_NATJ -13.53      0.00      3.25          -19.89           -7.17                0.00                0.00
cust_payment_terms_NATK -13.44      0.00      3.37          -20.04           -6.84                0.00                0.00
cust_payment_terms_NATL -13.85      0.00      3.29          -20.31           -7.40                0.00                0.00
cust_payment_terms_NATM -13.66      0.00      3.24          -20.01           -7.31                0.00                0.00
cust_payment_terms_NATU -13.57      0.00      3.37          -20.17           -6.98                0.00                0.00
cust_payment_terms_NATV -13.76      0.00      3.37          -20.36           -7.17                0.00                0.00
cust_payment_terms_NATW -13.82      0.00      3.25          -20.20           -7.44                0.00                0.00
cust_payment_terms_NATX -13.54      0.00      3.29          -19.99           -7.09                0.00                0.00
cust_payment_terms_NATZ -13.88      0.00      3.29          -20.33           -7.43                0.00                0.00
cust_payment_terms_NAU5 -12.40      0.00      2.79          -17.87           -6.93                0.00                0.00
cust_payment_terms_NAUP -12.91      0.00      3.22          -19.23           -6.59                0.00                0.00
cust_payment_terms_NAUW -11.29      0.00      2.80          -16.78           -5.81                0.00                0.00
cust_payment_terms_NAUY  -2.64      0.07      1.25           -5.09           -0.18                0.01                0.83
cust_payment_terms_NAUZ  -6.70      0.00      1.54           -9.71           -3.68                0.00                0.03
cust_payment_terms_NAV2  -2.61      0.07      0.95           -4.47           -0.75                0.01                0.47
cust_payment_terms_NAV9 -11.13      0.00      2.55          -16.12           -6.14                0.00                0.00
cust_payment_terms_NAVC -13.74      0.00      3.25          -20.12           -7.36                0.00                0.00
cust_payment_terms_NAVD -12.28      0.00      2.80          -17.77           -6.79                0.00                0.00
cust_payment_terms_NAVE -10.72      0.00      2.37          -15.36           -6.08                0.00                0.00
cust_payment_terms_NAVF  -8.57      0.00      1.95          -12.38           -4.76                0.00                0.01
cust_payment_terms_NAVL   0.72      2.05      0.59           -0.43            1.86                0.65                6.45
cust_payment_terms_NAVM  -2.92      0.05      0.77           -4.43           -1.41                0.01                0.24
cust_payment_terms_NAVQ  -6.67      0.00      1.53           -9.68           -3.67                0.00                0.03
cust_payment_terms_NAVR  -2.71      0.07      0.76           -4.20           -1.22                0.02                0.30
cust_payment_terms_NAWM -13.83      0.00      3.27          -20.23           -7.43                0.00                0.00
cust_payment_terms_NAWN  -4.73      0.01      1.13           -6.95           -2.51                0.00                0.08
cust_payment_terms_NAWP  -8.83      0.00      1.95          -12.65           -5.00                0.00                0.01
cust_payment_terms_NAWU  -9.14      0.00      2.09          -13.23           -5.04                0.00                0.01
cust_payment_terms_NAX2 -14.00      0.00      3.20          -20.28           -7.72                0.00                0.00
invoice_currency_USD      0.03      1.03      0.15           -0.27            0.33                0.77                1.39
segment_SME               0.07      1.08      0.02            0.04            0.11                1.04                1.11

                         cmp to      z      p  -log2(p)
covariate
total_open_amount          0.00   2.91 <0.005      8.11
days_to_due                0.00 -19.97 <0.005    292.39
invoice_age                0.00  -3.55 <0.005     11.34
avg_delay_customer         0.00 -16.09 <0.005    191.13
cust_payment_terms_B052    0.00  -3.97 <0.005     13.75
cust_payment_terms_BR12    0.00  -4.32 <0.005     15.99
cust_payment_terms_BR56    0.00  -4.40 <0.005     16.52
cust_payment_terms_C106    0.00  -4.26 <0.005     15.55
cust_payment_terms_C129    0.00  -0.11   0.91      0.13
cust_payment_terms_CA10    0.00  -4.39 <0.005     16.40
cust_payment_terms_CA30    0.00  -4.27 <0.005     15.63
cust_payment_terms_CA60    0.00  -3.58 <0.005     11.50
cust_payment_terms_CAB1    0.00  -4.18 <0.005     15.04
cust_payment_terms_CAX2    0.00  -4.71 <0.005     18.63
cust_payment_terms_MC15    0.00  -3.84 <0.005     12.99
cust_payment_terms_NA10    0.00  -4.29 <0.005     15.78
cust_payment_terms_NA25    0.00  -4.63 <0.005     18.03
cust_payment_terms_NA31    0.00  -3.84 <0.005     12.97
cust_payment_terms_NA32    0.00  -4.49 <0.005     17.10
cust_payment_terms_NA38    0.00  -4.53 <0.005     17.38
cust_payment_terms_NA3B    0.00  -4.32 <0.005     16.00
cust_payment_terms_NA3F    0.00  -4.33 <0.005     16.02
cust_payment_terms_NA84    0.00  -4.44 <0.005     16.78
cust_payment_terms_NA8Q    0.00  -4.16 <0.005     14.92
cust_payment_terms_NA9X    0.00  -4.36 <0.005     16.24
cust_payment_terms_NAA8    0.00  -4.44 <0.005     16.78
cust_payment_terms_NAAW    0.00  -4.32 <0.005     15.95
cust_payment_terms_NAAX    0.00  -4.41 <0.005     16.57
cust_payment_terms_NAB1    0.00  -4.05 <0.005     14.24
cust_payment_terms_NABD    0.00  -3.53 <0.005     11.22
cust_payment_terms_NABG    0.00  -4.57 <0.005     17.65
cust_payment_terms_NAC6    0.00  -4.46 <0.005     16.90
cust_payment_terms_NACB    0.00  -4.36 <0.005     16.21
cust_payment_terms_NACE    0.00  -0.20   0.84      0.25
cust_payment_terms_NACG    0.00  -0.12   0.90      0.15
cust_payment_terms_NACH    0.00  -0.25   0.81      0.31
cust_payment_terms_NAD1    0.00  -4.47 <0.005     17.00
cust_payment_terms_NAD4    0.00  -4.39 <0.005     16.45
cust_payment_terms_NAD5    0.00  -4.49 <0.005     17.08
cust_payment_terms_NAD8    0.00  -4.38 <0.005     16.33
cust_payment_terms_NAG2    0.00  -4.46 <0.005     16.93
cust_payment_terms_NAGD    0.00  -4.41 <0.005     16.58
cust_payment_terms_NAH4    0.00  -4.34 <0.005     16.07
cust_payment_terms_NAM1    0.00  -4.09 <0.005     14.48
cust_payment_terms_NAM2    0.00  -4.17 <0.005     15.03
cust_payment_terms_NAM3    0.00  -4.65 <0.005     18.21
cust_payment_terms_NAM4    0.00  -4.14 <0.005     14.82
cust_payment_terms_NATH    0.00  -4.20 <0.005     15.20
cust_payment_terms_NATJ    0.00  -4.17 <0.005     15.00
cust_payment_terms_NATK    0.00  -3.99 <0.005     13.89
cust_payment_terms_NATL    0.00  -4.21 <0.005     15.25
cust_payment_terms_NATM    0.00  -4.22 <0.005     15.29
cust_payment_terms_NATU    0.00  -4.03 <0.005     14.14
cust_payment_terms_NATV    0.00  -4.09 <0.005     14.49
cust_payment_terms_NATW    0.00  -4.25 <0.005     15.50
cust_payment_terms_NATX    0.00  -4.11 <0.005     14.64
cust_payment_terms_NATZ    0.00  -4.22 <0.005     15.31
cust_payment_terms_NAU5    0.00  -4.44 <0.005     16.78
cust_payment_terms_NAUP    0.00  -4.00 <0.005     13.97
cust_payment_terms_NAUW    0.00  -4.03 <0.005     14.16
cust_payment_terms_NAUY    0.00  -2.11   0.04      4.83
cust_payment_terms_NAUZ    0.00  -4.35 <0.005     16.19
cust_payment_terms_NAV2    0.00  -2.75   0.01      7.40
cust_payment_terms_NAV9    0.00  -4.37 <0.005     16.30
cust_payment_terms_NAVC    0.00  -4.22 <0.005     15.32
cust_payment_terms_NAVD    0.00  -4.38 <0.005     16.38
cust_payment_terms_NAVE    0.00  -4.53 <0.005     17.34
cust_payment_terms_NAVF    0.00  -4.41 <0.005     16.54
cust_payment_terms_NAVL    0.00   1.23   0.22      2.18
cust_payment_terms_NAVM    0.00  -3.78 <0.005     12.66
cust_payment_terms_NAVQ    0.00  -4.35 <0.005     16.18
cust_payment_terms_NAVR    0.00  -3.56 <0.005     11.41
cust_payment_terms_NAWM    0.00  -4.24 <0.005     15.42
cust_payment_terms_NAWN    0.00  -4.18 <0.005     15.06
cust_payment_terms_NAWP    0.00  -4.53 <0.005     17.34
cust_payment_terms_NAWU    0.00  -4.37 <0.005     16.33
cust_payment_terms_NAX2    0.00  -4.37 <0.005     16.28
invoice_currency_USD       0.00   0.20   0.84      0.25
segment_SME                0.00   4.63 <0.005     18.06
---
Concordance = 0.70
Partial AIC = 786433.63
log-likelihood ratio test = 4588.30 on 79 df
-log2(p) of ll-ratio test = inf